config/routes.rb
Rails.application.routes.draw do
  root to: 'sessions#new'
  resources :projects do
    collection { post :sort }
  end
  resources :tasks do
    collection { post :sort }
  end
  resources :users
  get    'signup'  => 'users#new',        as: :signup
  get    'signin'  => 'sessions#new',     as: :signin
  post   'signin'  => 'sessions#create'
  delete 'signout' => 'sessions#destroy', as: :signout
end

app/models/project.rb
class Project < ActiveRecord::Base
  validates  :name, presence: true
  has_many   :tasks, dependent: :destroy
  belongs_to :user
end

app/models/task.rb
class Task < ActiveRecord::Base
  validates :name, presence: true

  belongs_to :project

  def self.incomplete
    where(done: false).order('priority')
  end

  def self.complete
    where(done: true).order('updated_at')
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
  before_save { self.email = email.downcase }
  validates :email, presence: true, format: { with: VALID_EMAIL_REGEX },
                                    uniqueness: { case_sensitive: false }
  validates :password, length: { minimum: 6 }
  has_secure_password
  has_many :projects
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :authenticate_user

  def index
    @projects = current_user.projects.order('priority')
    @task = Task.new
  end

  def show
    @project = Project.find_by_id(params[:id])
    respond_to do |format|
      format.html { redirect_to projects_path }
      format.js
    end
  end

  def new
    @project = Project.new
  end

  def create
    @project = current_user.projects.create(project_params)
    @task = Task.new
    respond_to do |format|
      format.html { redirect_to projects_path }
      format.js
    end
  end

  def update
    @project = Project.find_by_id(params[:id])
    respond_to do |format|
      if @project.update_attributes(project_params)
        format.html { redirect_to projects_path }
        format.json { respond_with_bip(@project) }
      else
        format.html { redirect_to projects_path }
        format.json { respond_with_bip(@project) }
      end
    end
  end

  def destroy
    @project = Project.destroy(params[:id])
    respond_to do |format|
      format.html { redirect_to projects_path }
      format.js
    end
  end

  def sort
    params[:project].each_with_index do |id, index|
      Project.where(id: id).update_all({priority: index+1})
    end
    render nothing: true
  end

  private

  def project_params
    params.require(:project).permit(:name)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  before_action :registered_user, only: [:new, :create]

  def new
  end

  def create
    @user = User.find_by(email: params[:session][:email])
    if @user && @user.authenticate(params[:session][:password])
      session[:user_id] = @user.id
      redirect_to projects_path
    else
      flash.now[:danger] = "Invalid combination Email/Password."
      render 'new'
    end
  end

  def destroy
    session.delete(:user_id)
    @current_user = nil
    redirect_to root_path
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def new
  end

  def create
    @task = Task.new(task_params)
    @task.project_id = params[:project_id]
    @task.save
    respond_to do |format|
      format.html { redirect_to projects_path }
      format.js
    end
  end

  def update
    @task = Task.find_by_id(params[:id])
    respond_to do |format|
      if @task.update_attributes(task_params)
        format.html { redirect_to projects_path }
        format.json { head :ok }
        format.js
      else
        format.html { redirect_to projects_path }
        format.json { respond_with_bip(@task) }
      end
    end
  end

  def destroy
    @task = Task.destroy(params[:id])
    respond_to do |format|
      format.html { redirect_to projects_path }
      format.js
    end
  end

  def sort
    params[:edit_task].each_with_index do |id, index|
      Task.where(id: id).update_all({priority: index+1})
    end
    render nothing: true
  end

  private

  def task_params
    params.require(:task).permit(:name, :done, :deadline)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :registered_user

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:success] = "Welcome aboard!"
      session[:user_id] = @user.id
      redirect_to projects_path
    else
      flash.now[:danger] = "The form contains some errors."
      render 'new'
    end
  end

  private

  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  # Returns the Gravatar (http://gravatar.com/) for the given user.
  def gravatar_for(user, options = { size: 40 })
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, class: "gravatar")
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    current_user != nil
  end

  def test

  end

  private

  def authenticate_user
    redirect_to signin_path unless logged_in?
  end

  def registered_user
    redirect_to projects_path if logged_in?
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Simple Todo Lists</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>
<% flash.each do |key, value| %>
  <div class="purr alert alert-<%= key %>" role="<%= key %>"><%= value %></div>
<% end %>

<% if logged_in? %>
  <div class="profile">
    <div class="avatar">
      <%= gravatar_for current_user %>
    </div>
    <div class="signout">
      <p><b><%= current_user.email %></b></p>
      <p><%= link_to "Sign out", signout_path, method: :delete %></p>
    </div>
  </div>
<% end %>
<h1>Simple Todo Lists</h1>

<div class="container">
  <%= yield %>
</div>

</body>
</html>

app/views/projects/_form.html.erb
<%= form_for @project, remote: true do |f| %>
<div class="row">
  <div class="col-xs-12">
    <div class="input-group input-group-lg">
      <%= f.text_field :name, placeholder: "Enter Project name",
                              autofocus: true, class: "form-control",
                              required: true %>
      <div class="input-group-btn">
        <%= f.submit "Create", class: "btn btn-primary" %>
      </div>
    </div>
  </div>
</div>
<% end %>

app/views/projects/_options.html.erb
<%= link_to project_path(project), remote: true do %>
  <span class="glyphicon glyphicon-ok" aria-hidden="true"></span>
<% end %>
&nbsp;
<%= link_to 'javascript:void(0)', class: "handle" do %>
  <span class="glyphicon glyphicon-move" aria-hidden="true"></span>
<% end %>
&nbsp;
<%= link_to 'javascript:void(0)', id: "edit_project_#{project.id}" do %>
  <span class="glyphicon glyphicon-pencil" aria-hidden="true"></span>
<% end %>
&nbsp;
<%= link_to project_path(project), method: :delete, remote: true,
                                   data: { confirm: "Are you sure?" },
                                   id: "delete_project_#{project.id}" do%>
  <span class="glyphicon glyphicon-trash" aria-hidden="true"></span>
<% end %>

app/views/projects/_project.html.erb
<div class="panel panel-primary" id="project_<%= project.id %>">
  <div class="panel-heading">
    <div class="div-project-name">
      <span class="glyphicon glyphicon-calendar" aria-hidden="true"></span>&nbsp;
      <%= best_in_place project, :name, activator: "#edit_project_#{project.id}" %>
    </div>
    <div class="div-project-options">
      <%= render 'options', project: project %>
    </div>
  </div>
  <div class="new-task">
    <%= form_for @task, remote: true do |f| %>
      <div class="row">
        <div class="col-xs-12">
          <div class="input-group">
            <div class="input-group-addon"><span class="glyphicon glyphicon-plus" aria-hidden="true"></span></div>
            <%= hidden_field_tag(:project_id, project.id) %>
            <%= f.text_field :name, class: "form-control", required: true,
                             placeholder: "Start typing here to create a task..." %>
            <div class="input-group-btn">
              <%= f.submit "Add Task", class: "btn btn-success" %>
            </div>
          </div>
        </div>
      </div>
    <% end %>
  </div>
  <div class="list-group">
    <div class="incomplete_tasks" data-update-url="<%= sort_tasks_url %>">
      <%= render project.tasks.incomplete %>
    </div>
    <div class="complete_tasks">
      <%= render project.tasks.complete %>
    </div>
  </div>
</div>

app/views/projects/create.js.erb
$('#new_project').remove();
$('#new_link').show();
$('#all_projects').prepend('<%= j render(@project) %>');
$('html, body').animate({ scrollTop: 0 }, 'slow');

app/views/projects/destroy.js.erb
$('#project_<%= @project.id %>').remove();

app/views/projects/index.html.erb
<div class="row">
  <div class="col-md-6 col-md-offset-3" id="all_projects" data-update-url="<%= sort_projects_url %>">
    <%= render @projects %>
  </div>
  <div class="col-md-6 col-md-offset-3">
    <div class="new-project">
      <%= link_to new_project_path, class: "btn btn-primary btn-lg",
                                    id: "new_link", remote: true do %>
      <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>
      Add TODO List
      <% end%>
    </div>
  </div>
</div>

app/views/projects/new.js.erb
$('#new_link').hide().after('<%= j render("form") %>')

app/views/projects/show.js.erb
$('#project_<%= @project.id %> .complete_tasks').toggle("slow", function() {});

app/views/tasks/_options.html.erb
<%= link_to 'javascript:void(0)', id: "set_deadline_#{task.id}"  do %>
  <span class="glyphicon glyphicon-time" aria-hidden="true"></span>
<% end %>
&nbsp;
<%= link_to 'javascript:void(0)', class: "handle" do %>
  <span class="glyphicon glyphicon-move" aria-hidden="true"></span>
<% end %>
&nbsp;
<%= link_to 'javascript:void(0)', id: "edit_inline_#{task.id}" do %>
  <span class="glyphicon glyphicon-pencil" aria-hidden="true"></span>
<% end %>
&nbsp;
<%= link_to task_path(task), method: :delete, remote: true,
                             data: { confirm: "Are you sure?" },
                             id: "delete_task_#{task.id}" do %>
  <span class="glyphicon glyphicon-trash" aria-hidden="true"></span>
<% end %>

app/views/tasks/_task.html.erb
<%= form_for task, remote: true do |f| %>
  <%= content_tag_for :div, task, class: "list-group-item" do %>
    <div class="div-check">
      <%= f.check_box :done, id: "task_complete_#{task.id}" %>
      <%= f.submit "Update" %>
    </div>
    <div class="div-label">
      <%= f.label "complete_#{task.id}", class: "task-label#{' complete' if task.done?}" do %>
        <%= best_in_place task, :name, activator: "#edit_inline_#{task.id}" %>
        <%= best_in_place(task, :deadline, activator: "#set_deadline_#{task.id}",
                          as: :date, class: "datepicker",
                          display_with: lambda { |dt| dt.strftime("%Y-%m-%d") if !dt.nil? }) %>
      <% end %>
    </div>
    <div class="div-options">
      <%= render 'tasks/options', task: task %>
    </div>
  <% end %>
<% end %>

app/views/tasks/create.js.erb
$('#project_<%= @task.project.id %> #task_name').val('');
$('#project_<%= @task.project.id %> .incomplete_tasks').prepend('<%= j render(@task) %>');
$('#edit_task_<%= @task.id %>').submitOnCheck();
$('.best_in_place').best_in_place();
$('.incomplete_tasks').sortable({
  axis: 'y',
  handle: '.handle',
  update: function() {
    return $.post($(this).data('update-url'), $(this).sortable('serialize'));
  }
});

app/views/tasks/destroy.js.erb
$('#edit_task_<%= @task.id %>').remove();

app/views/tasks/update.js.erb
<% if @task.done? %>
  $('#edit_task_<%= @task.id %>').prependTo('#project_<%= @task.project.id %> .complete_tasks');
  $('#edit_task_<%= @task.id %> label').addClass('complete');
<% else %>
  $('#edit_task_<%= @task.id %>').prependTo('#project_<%= @task.project.id %> .incomplete_tasks');
  $('#edit_task_<%= @task.id %> label').removeClass('complete');
<% end %>

app/views/users/_errors.html.erb
<div class="errors">
  <% if @user.errors.any? %>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  <% end %>
</div>

app/views/users/new.html.erb
<div class="row">
  <div class="col-md-4 col-md-offset-4">
    <h2>Sign up</h2>
    <%= form_for @user, validate: true do |f| %>
      <%= render 'errors'%>
      <div class="form-group">
        <%= f.label :email %>
        <%= f.email_field :email, class: "form-control", autofocus: true %>
      </div>
      <div class="form-group">
        <%= f.label :password %>
        <%= f.password_field :password, class: "form-control" %>
      </div>
      <div class="form-group">
        <%= f.label :password_confirmation %>
        <%= f.password_field :password_confirmation, class: "form-control" %>
      </div>
      <%= f.submit "Sign up!", class: "btn btn-primary" %>
    <% end %>
    <p class="form-link"><%= link_to "Already have an account", signin_path %></p>
  </div>
</div>